CREATE TABLE diagnostic (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    note VARCHAR(255) NOT NULL,
    cid_id VARCHAR(255) NOT NULL,
    created_at TIMESTAMP ,
    updated_at TIMESTAMP ,
    deleted_at TIMESTAMP
);
